[build]
builder = "DOCKERFILE"
dockerfilePath = "../Dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
projectId = "ec1ccb72-fb04-4d48-b079-3e2eb12af14a"
